### ISSUE TITLE
弹幕用户和发送时间？

### ISSUE THREAD

**Issue by chentc** [tiansh/us-danmaku#11]
能不能考虑加入弹幕用户和发送弹幕的时间？

**Comment by tiansh** [comment]
加入到哪里？弹幕后面跟着作者和时间？

**Comment by chentc** [comment]
是的 可以抓到这个数据吧？这个B站的弹幕爬虫可以爬到 https://github.com/Vespa314/bilibili-api, 不知A站有没有开放这个。应该起码有发表时间的先后顺序。

**Comment by tiansh** [comment]
数据都有，但是你要怎么展现这些数据呢？每条弹幕后面跟着作者，看起来不会怪怪的吗？

**Comment by chentc** [comment]
我现在的需求是从后台分析弹幕，不用加载到视频上看。比如下面是我从B站抓到的数据，

`0.0,2015-12-22 09:21:33,方法,D9e9031f,1,FFFFFF
0.0,2015-12-22 09:21:47,发给,D9e9031f,1,FFFFFF
0.0,2015-12-24 10:52:28,来看朋友说的根本到不到那个高度,daf86559,1,FFFFFF
0.0,2015-12-24 20:26:34,超级好看,58ee927d,1,FFFFFF
0.0,2015-12-25 21:37:42,㐃,D4e268f5,1,FFFFFF
0.0,2015-12-26 14:15:54,20151226,1f4ce0b3,1,FFFFFF
0.0,2015-12-27 05:34:15,细细看，感动的一塌糊涂。,5962b57a,1,FFFFFF`

这里就有弹幕在电影里面的时间，发布时间，弹幕内容，用户和颜色。

@tiansh 能不能给我指点一下js这块数据怎么加上去 然后我再从ass转成我的格式也成。

**Comment by tiansh** [comment]
我觉得你把代码里面parseXML函数拷贝出来，配合下载的xml文件用估计就够了。

**Comment by chentc** [comment]
搞定了 我整合了一个Python脚本放在这里 可以爬A站B站的弹幕 https://github.com/chentc/bilibili_crawl
