### ISSUE TITLE
能否支持 bangumi.bilibili.com/anime/v/* 页面？

### ISSUE THREAD

**Issue by microka** [tiansh/us-danmaku#14]
http://bangumi.bilibili.com/anime/v/43990
比如这个，希望作者能添加这类页面的弹幕下载解析。

**Comment by tiansh** [comment]
这页面出来有一段时间了，一直没支持这个页面的原因有两个：
# 网页上面有个 AVxxxx 的链接，点过去就可以用了；
# 网页的布局和原来的不同，原来的那个下载按钮的样式不适合新网页，而我又懒的设计一个新的按钮画上去

如果有人愿意给我设计一个适用于这个网页的下载按钮的图标给我，我倒是不介意支持这种版面……

不过现在处于懒的弄的情况……

**Comment by microka** [comment]
get!! 能下载就好了，非常感谢！
