### ISSUE TITLE
某个视频无法抓取弹幕

### ISSUE THREAD

**Issue by microka** [tiansh/us-danmaku#19]
**1.11**: 
http://www.bilibili.com/video/av6964274/ 无法抓取弹幕，请问是什么原因？

**Comment by myfreeer** [comment]
因为部分白色从`16777215`改成了`4294967295`，导致脚本试图构建长度为`-1`的Array
[bilibili_ASS_Danmaku_Downloader.user.js#L62](https://github.com/tiansh/us-danmaku/blob/0488b957855dda3c1bb3e37a6941c948b4a76362/bilibili/bilibili_ASS_Danmaku_Downloader.user.js#L62)
