### ISSUE TITLE
A站UI更新，页面下载按钮失效

### ISSUE THREAD

**Issue by LilHayah** [tiansh/us-danmaku#6]
公告见
http://www.acfun.tv/a/ac1799364

A站最近更新了UI设计，原来页面上使用插件直接下载的按钮失效。

**Comment by tiansh** [comment]
谢谢提醒，明天早上起来看看。
是不是说只是没有按钮，但是转换功能还正常？

**Comment by LilHayah** [comment]
转换应该正常。就是因为UI改变，按钮失踪了。

**Comment by tiansh** [comment]
在视频下面加了一个按钮，如果还不正常请回复告知。
