### ISSUE TITLE
页面下载插件不支持ab开头的视频

### ISSUE THREAD

**Issue by LilHayah** [tiansh/us-danmaku#7]
比如 http://www.acfun.tv/v/ab1470127_12
需要手动到source里面找到data-vid="*"里的数字加到 http://static.comment.acfun.mm111.net/ 后面下载json然后再手动转换ass

**Comment by tiansh** [comment]
我有日子没上AB俩站了，明天一早去看看这俩问题。不过ab开头是怎么回事？都有哪些开头，除了ab、ac还有什么吗？

**Comment by tiansh** [comment]
应该已经解决，如有问题请回复告知。
