### ISSUE TITLE
AcFun ASS Danmaku Downloader弹幕下载按钮消失了

### ISSUE THREAD

**Issue by winovic** [tiansh/us-danmaku#9]
浏览器chrome 46.0.2490.80 ，firefox 42.0.0
系统mac osx 10.10
a站弹幕下载按钮消失了，b站正常

**Comment by tiansh** [comment]
12 版本应该已经更新了。
原因是 AcFun 使用了新的弹幕服务器域名，现在的弹幕是从 danmu.aixifan.com 得到的……

**Comment by winovic** [comment]
啊已恢复
感谢感谢

**Comment by winovic** [comment]
Hello!

 

You have a new message, please read <http://climberbrasov.ro/score.php?q9c>

 

oxwinovicxo@yahoo.com

**Comment by winovic** [comment]
Hello, 


Have you already seen that great stuff  I've just found on the web? You should  definitely take a look <http://friend.averillwoods.org/lnnkar>

Best regards, oxwinovicxo
